#ifndef INTEL_HDA_ROUTE_STATUS_H
#define INTEL_HDA_ROUTE_STATUS_H
#define INTEL_HDA_ROUTE_PARAMETER "IntelHDAOutputRoute"
#define INTEL_HDA_ROUTES_PARAMETER "IntelHDAOutputRoutes"
#define INTEL_HDA_ROUTE_SCHEMA 1U
#define HDA_ROUTE_HEADER 20U
#define HDA_ROUTE_ROW 18U
#define HDA_ROUTE_STATUS_MAX (HDA_ROUTE_HEADER + 16U * HDA_ROUTE_ROW)
enum {
    HDA_RS_SCHEMA, HDA_RS_COUNT, HDA_RS_REQUESTED_PIN, HDA_RS_APPLIED_PIN,
    HDA_RS_ACTIVE_PIN, HDA_RS_REQUEST, HDA_RS_COMPLETED, HDA_RS_RESULT,
    HDA_RS_CHANGES, HDA_RS_FAILURES, HDA_RS_ROLLBACKS, HDA_RS_UNSAFE,
    HDA_RS_READ_OK, HDA_RS_READ_TICK, HDA_RS_SENSE_ERRORS,
    HDA_RS_MUTE, HDA_RS_LEFT, HDA_RS_RIGHT, HDA_RS_FORMAT, HDA_RS_RUNNING
};
enum {
    HDA_RR_PIN, HDA_RR_DAC, HDA_RR_DEVICE, HDA_RR_DETECTABLE, HDA_RR_PRESENT,
    HDA_RR_SENSE, HDA_RR_CONTROL, HDA_RR_FORMAT, HDA_RR_CHANNEL, HDA_RR_EAPD,
    HDA_RR_AMP_LEFT, HDA_RR_AMP_RIGHT, HDA_RR_RATES, HDA_RR_VOLUME_NID,
    HDA_RR_MUTE_NID, HDA_RR_MUTE_LEFT, HDA_RR_MUTE_RIGHT, HDA_RR_VOLUME_CAPS
};
#endif
