#ifndef INTEL_HDA_STATS_H
#define INTEL_HDA_STATS_H
#define INTEL_HDA_DRIVER_VERSION "0.18"
#define INTEL_HDA_STATS_PARAMETER "IntelHDAInterruptStats"
#define INTEL_HDA_STATS_SCHEMA_VERSION 3U
#define INTEL_HDA_MODE_MSI 1U
#define INTEL_HDA_MODE_POLLING 2U
typedef enum IntelHDAStatsIndex {
    INTEL_HDA_STAT_SCHEMA,
    INTEL_HDA_STAT_MODE,
    INTEL_HDA_STAT_RUNNING,
    INTEL_HDA_STAT_FIRMWARE_INTERRUPT_LINE,
    INTEL_HDA_STAT_MSI_VECTOR,
    INTEL_HDA_STAT_MSI_CAP,
    INTEL_HDA_STAT_MSIX_CAP,
    INTEL_HDA_STAT_MSI_ALLOCATED,
    INTEL_HDA_STAT_MSI_ENABLED,
    INTEL_HDA_STAT_MSI_ACTIVE,
    INTEL_HDA_STAT_NOTIFICATIONS,
    INTEL_HDA_STAT_SERVICE_PASSES,
    INTEL_HDA_STAT_CONSUMES,
    INTEL_HDA_STAT_ACKNOWLEDGMENTS,
    INTEL_HDA_STAT_CONSUMED_MESSAGES,
    INTEL_HDA_STAT_EPOCH_FAILURES,
    INTEL_HDA_STAT_GATE_RESULT,
    INTEL_HDA_STAT_COMPLETED_PERIODS,
    INTEL_HDA_STAT_STREAM_ERRORS,
    INTEL_HDA_STAT_IGNORED_MESSAGES,
    INTEL_HDA_STAT_QUARANTINED,
    INTEL_HDA_STAT_POLL_TICKS,
    INTEL_HDA_STAT_POLL_COMPLETIONS,
    INTEL_HDA_STAT_PROMPT_REQUESTED,
    INTEL_HDA_STAT_PROMPT_ACTIVE,
    INTEL_HDA_STAT_PROMPT_RESULT,
    INTEL_HDA_STAT_REBOOT_REQUIRED,
    INTEL_HDA_STAT_DISABLE_FAILURES,
    INTEL_HDA_STAT_RELEASE_FAILURES,
    INTEL_HDA_STAT_PCI_ID,
    INTEL_HDA_STAT_CODEC_ID,
    INTEL_HDA_STAT_PIN,
    INTEL_HDA_STAT_DAC,
    INTEL_HDA_STAT_DMA_BYTES,
    INTEL_HDA_STAT_PERIOD_BYTES,
    INTEL_HDA_STAT_INTCTL,
    INTEL_HDA_STAT_PCI_COMMAND,
    INTEL_HDA_STAT_MSI_CONTROL,
    INTEL_HDA_STAT_MSIX_CONTROL,
    INTEL_HDA_STATS_COUNT
} IntelHDAStatsIndex;
#endif
