MAKEFILEDIR = /NextDeveloper/Makefiles/driverkit
MAKEFILE = Makefile.main_driver

PRIVATE_DEFINES = -DKERNEL_PRIVATE -DDRIVER_PRIVATE
OTHER_CFLAGS = -Wall -Wno-unused -no-precomp \
	$(PRIVATE_DEFINES)
