#
# Generated-style OPENSTEP DriverKit main driver makefile.
#

NAME = IntelHDA_reloc

PROJECTVERSION = 1.1
LANGUAGE = English

CLASSES = IntelHDAController.m IntelHDADriver.m

HFILES = IntelHDAController.h IntelHDADriver.h

OTHERSRCS = Makefile.preamble Makefile Makefile.postamble\
            Load_Commands.sect Makefile.driver_preamble

MAKEFILEDIR = /NextDeveloper/Makefiles/app
MAKEFILE = tool.make
SOURCEMODE = 444

LIBS =
DEBUG_LIBS = $(LIBS)
PROF_LIBS = $(LIBS)

-include Makefile.preamble

include $(MAKEFILEDIR)/$(MAKEFILE)

-include Makefile.postamble

-include Makefile.dependencies
